import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  variable: "--font-poppins", // Creamos una variable CSS para Poppins
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // Especificamos los pesos
});

export const metadata = {
  title: "Event Management",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={` ${poppins.variable} antialiased`}>{children}</body>
    </html>
  );
}
